### ISSUE TITLE
steps on the way to get this into opencv_contrib

### ISSUE THREAD

**Issue by berak** [vrsb2006/FaceFeat#2]
hi ;)

wow, your result images are entirely nice, you're definitely on to something there.
* all code should be (re)based on latest 3.4 or master branch
* since it should go into https://github.com/opencv/opencv_contrib/modules/face, you should follow the structure there, which is: 

```
C:\P\OPENCV_CONTRIB\MODULES\FACE
├───data // dunno. maybe you have  to put it on opencv_extra
├───doc // please.
├───include
│   └───opencv2
│       └───face // if you really implement the "Facemark" interface, only a "factory function" is needed here.
├───samples // whatever is in main() now
├───src // maybe rename "utils.cpp" to "FaceFeat.cpp" or such, and put it here ?
├───test  // add at least some "smoke tests"
└───tutorials // please 
```
in the long run, you'll have to *fork* the opencv_contrib repo, make a newbranch with your changes, and  do a pull-request with those.
 
* so, you got a `live()` function, but if you want to get it into a *library*, this is doing too much.
can you try to implement the [Facemark interface](https://github.com/opencv/opencv_contrib/blob/2231018c839d728811a39556ec83741bf9a27614/modules/face/include/opencv2/face/facemark.hpp#L47) instead ? (images may come from anywhere, don't restrict folks to using a webcam),  and probably, *writing*  a video should be left to users, too.
also be prepared for *multiple* face detections (that's why it has a `vector<vector<Point2d>>` in the `fit()` function (you don't need to do anyface *detection*. again leave *that* to the users.
also, if you do so, this will make your code automatically available to python / java / matlab users.

* loading the yml files takes ages (15 seconds) a simple ifstream/ofstream serialization would reduce it to fractions of a second, and result in much smaller file size (25mb for all of it)
* is there any paper ? (curious, what the HOGDescriptor is doing there)
* it's pretty exact, but somewhat slow (0.25 sec per detection here) main offenders are the large matrix multiplications, and ofc. the HOGDescriptors

* i had some fun, playing with your code and trying to adapt it to the Facemark interface, [have a look here, please](https://gist.github.com/berak/4cc06224f6620cfec9616a142a26fcd7)

**Comment by vrsb2006** [comment]
Hi berak,

Thanks you for writing. It is very much valuable. :)

Addressing your points:

1) Agreed. I will try to look into it. One thing I want to mention here is that the facial detection system is very much sensitive to intialization. So, I am not sure that how it will perform with other face detection classifiers. I used haarcascade_frontalface_alt2.xml for training.

2) I was thinking of similar kind of thing (serialization). I will try to complete it asap.

3) I added references to main readme.md. 

4) I tested this code in my machine with opencv's release dlls. It was taking around 0.067 secs per frame (assume processing only one face). It might probably due to openMP parallel directive I used inside HOG feature detection function. But yeah, you are absolutely right. The code can be optimized a lot. I will look into it.

5) It is very interesting. I will give it try and let you know.

Again, Thanks for so much your generosity.
Have a good day.  :)

**Comment by berak** [comment]
any updates ? just curious ...

**Comment by vrsb2006** [comment]
Hi berak,

I was working on improving the performance of facial point detector. But I am little off from the work from past few weeks due to bad health. 

I will continue again after recovery.

Thanks for the message. :)

**Comment by vrsb2006** [comment]
Hi berak, 

I have a doubt. It seems that author of algorithm used for this implementation has a [patent](https://patents.google.com/patent/US9659210) for this approach. Can I still contribute ??

**Comment by berak** [comment]
ohh, i'm no expert at that.

maybe ask the authors for permission ?

(there *are* some patented algorithms in opencv_contrib, SIFT,SURF, B3dm, and it's possible to disable those with a cmake flag during the compilation, if nessecary)

**Comment by vrsb2006** [comment]
I've mailed [Xuehan Xiong](http://xiong828.github.io/index.html) (author). Let's see, what he will say.
